# Generated by Django 4.1.6 on 2023-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_upload_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=25)),
                ('productname', models.CharField(max_length=25)),
                ('productamount', models.IntegerField()),
                ('productdetails', models.CharField(max_length=100)),
                ('productimage', models.FileField(upload_to='')),
            ],
        ),
    ]
