# Generated by Django 4.1.6 on 2023-03-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0002_product_upload_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_upload_tbl',
            name='productimage',
            field=models.FileField(upload_to='pictures'),
        ),
    ]
