# Generated by Django 4.1.6 on 2023-03-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0003_alter_product_upload_tbl_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_upload_tbl',
            name='sellerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itemseller.itemseller_reg_tbl'),
            preserve_default=False,
        ),
    ]
