# Generated by Django 4.1.6 on 2023-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0004_product_upload_tbl_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_upload_tbl',
            name='sellername',
            field=models.CharField(max_length=100),
        ),
    ]
