# Generated by Django 4.1.6 on 2023-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0005_alter_product_upload_tbl_sellername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_upload_tbl',
            name='sellerid',
            field=models.IntegerField(),
        ),
    ]
