# Generated by Django 4.1.6 on 2023-04-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0007_itemseller_reg_tbl_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_upload_tbl',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itemseller.itemseller_reg_tbl'),
            preserve_default=False,
        ),
    ]
