# Generated by Django 4.1.6 on 2023-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0008_product_upload_tbl_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_upload_tbl',
            name='status',
            field=models.CharField(default='stock available', max_length=25),
        ),
    ]
