# Generated by Django 4.1.6 on 2023-04-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0009_product_upload_tbl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_upload_tbl',
            name='seller',
            field=models.ForeignKey(default='seller account deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='itemseller.itemseller_reg_tbl'),
        ),
    ]
