# Generated by Django 4.1.6 on 2023-05-09 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0010_alter_product_upload_tbl_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_upload_tbl',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemseller.itemseller_reg_tbl'),
        ),
    ]
