# Generated by Django 4.1.2 on 2023-07-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itemseller", "0011_alter_product_upload_tbl_seller"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=100)),
            ],
        ),
    ]
