# Generated by Django 4.1.2 on 2023-07-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("itemseller", "0012_pcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_upload_tbl",
            name="catid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="itemseller.pcategory",
            ),
            preserve_default=False,
        ),
    ]
