# Generated by Django 4.1.6 on 2023-03-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('Age', models.CharField(max_length=3)),
                ('mobile', models.IntegerField(max_length=11)),
                ('Address', models.CharField(max_length=60)),
                ('Gender', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
            ],
        ),
    ]
