# Generated by Django 4.1.6 on 2023-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_manager_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reg_tbl',
            name='emid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
