# Generated by Django 4.1.6 on 2023-04-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_event_reg_tbl_ticker_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_reg_tbl',
            old_name='ticker_amount',
            new_name='ticket_amount',
        ),
    ]
