# Generated by Django 4.1.6 on 2023-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_rename_ticker_amount_event_reg_tbl_ticket_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reg_tbl',
            name='status',
            field=models.CharField(default='not change', max_length=50),
        ),
    ]
