# Generated by Django 4.1.6 on 2023-04-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_alter_event_reg_tbl_edate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_manager_tbl',
            name='Approve',
            field=models.BooleanField(default=False),
        ),
    ]
