# Generated by Django 4.1.6 on 2023-04-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_event_manager_tbl_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reg_tbl',
            name='em',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Event.event_manager_tbl'),
            preserve_default=False,
        ),
    ]
