# Generated by Django 4.1.6 on 2023-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turf_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('taddress', models.TextField()),
                ('dist', models.CharField(max_length=25)),
                ('temail', models.EmailField(max_length=50)),
                ('tmob', models.CharField(max_length=20)),
                ('ps1', models.CharField(max_length=25)),
                ('ps2', models.CharField(max_length=25)),
            ],
        ),
    ]
