# Generated by Django 4.1.6 on 2023-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_reg_tbl',
            name='timg',
            field=models.FileField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
