# Generated by Django 4.1.6 on 2023-04-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0004_slot_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_tbl',
            name='etime',
            field=models.TimeField(),
        ),
    ]
