# Generated by Django 4.1.6 on 2023-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0008_slot_tbl_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_tbl',
            name='status',
            field=models.CharField(default='no issue', max_length=50),
        ),
    ]
