# Generated by Django 4.1.6 on 2023-04-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0009_alter_slot_tbl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_reg_tbl',
            name='Approve',
            field=models.BooleanField(default=False),
        ),
    ]
