# Generated by Django 4.1.6 on 2023-04-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=100)),
                ('Adetails', models.TextField()),
                ('Address', models.TextField()),
                ('Aloc', models.URLField()),
                ('status', models.CharField(default='seat available', max_length=50)),
                ('Aemail', models.EmailField(max_length=254, unique=True)),
                ('Amob', models.IntegerField()),
                ('Approve', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=12)),
                ('cpass', models.CharField(max_length=12)),
            ],
        ),
    ]
