# Generated by Django 4.1.6 on 2023-04-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academy_reg',
            new_name='Academy_reg_tbl',
        ),
    ]
