# Generated by Django 4.1.6 on 2023-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_rename_academy_reg_academy_reg_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_reg_tbl',
            name='Aimg',
            field=models.FileField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
