# Generated by Django 4.1.6 on 2023-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0003_academy_reg_tbl_aimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_reg_tbl',
            name='dist',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
