# Generated by Django 4.1.6 on 2023-04-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0004_academy_reg_tbl_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_reg_tbl',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
    ]
