# Generated by Django 4.1.6 on 2023-03-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_regtbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('mob', models.IntegerField()),
                ('ag', models.IntegerField()),
                ('ad', models.TextField()),
                ('gn', models.CharField(max_length=10)),
                ('eml', models.EmailField(max_length=254)),
                ('ps1', models.CharField(max_length=25)),
                ('ps2', models.CharField(max_length=25)),
            ],
        ),
    ]
