# Generated by Django 4.1.6 on 2023-03-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0006_alter_product_upload_tbl_sellerid'),
        ('User', '0002_add_to_cart_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemseller.product_upload_tbl')),
            ],
        ),
        migrations.DeleteModel(
            name='Add_to_cart_tbl',
        ),
    ]
