# Generated by Django 4.1.6 on 2023-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_add_to_cart_table_delete_add_to_cart_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart_table',
            name='proid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
