# Generated by Django 4.1.6 on 2023-04-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0006_alter_product_upload_tbl_sellerid'),
        ('User', '0004_add_to_cart_table_proid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('arrival_date', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemseller.product_upload_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_regtbl')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
