# Generated by Django 4.1.6 on 2023-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shipping_Address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
