# Generated by Django 4.1.6 on 2023-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_booking_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Alt_phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
