# Generated by Django 4.1.6 on 2023-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_booking_alt_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
