# Generated by Django 4.1.6 on 2023-04-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_booking_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 18, 33, 37, 245092)),
        ),
    ]
