# Generated by Django 4.1.6 on 2023-04-03 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemseller', '0006_alter_product_upload_tbl_sellerid'),
        ('User', '0012_alter_booking_arrival_date_alter_booking_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 13, 22, 53, 311663)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 13, 22, 53, 311663)),
        ),
        migrations.CreateModel(
            name='complaint_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(default=datetime.datetime(2023, 4, 3, 13, 22, 53, 311663))),
                ('cimage', models.FileField(upload_to='pictures')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemseller.product_upload_tbl')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemseller.itemseller_reg_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_regtbl')),
            ],
        ),
    ]
