# Generated by Django 4.1.6 on 2023-04-03 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_booking_arrival_date_alter_booking_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_reg_tbl',
            name='product',
        ),
        migrations.RemoveField(
            model_name='complaint_reg_tbl',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint_reg_tbl',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 25, 10, 367535)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 14, 25, 10, 367535)),
        ),
        migrations.AlterField(
            model_name='complaint_reg_tbl',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 14, 25, 10, 367535)),
        ),
    ]
