# Generated by Django 4.1.6 on 2023-04-03 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_remove_complaint_reg_tbl_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_reg_tbl',
            name='status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 54, 10, 911046)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 14, 54, 10, 911046)),
        ),
        migrations.AlterField(
            model_name='complaint_reg_tbl',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 14, 54, 10, 911046)),
        ),
    ]
