# Generated by Django 4.1.6 on 2023-04-06 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_booking_arrival_date_alter_booking_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 19, 56, 50, 47456)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 19, 56, 50, 47456)),
        ),
        migrations.AlterField(
            model_name='complaint_reg_tbl',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
