# Generated by Django 4.1.6 on 2023-04-06 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_alter_booking_arrival_date_alter_booking_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 23, 19, 12, 942911)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 23, 19, 12, 942911)),
        ),
        migrations.AlterField(
            model_name='user_regtbl',
            name='eml',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
