# Generated by Django 4.1.6 on 2023-04-11 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_alter_booking_arrival_date_alter_booking_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 11, 54, 59, 741760)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 11, 54, 59, 741760)),
        ),
    ]
