# Generated by Django 4.1.6 on 2023-04-18 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_event_reg_tbl_status'),
        ('User', '0024_alter_booking_arrival_date_alter_booking_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 12, 16, 36, 69752)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 12, 16, 36, 69752)),
        ),
        migrations.CreateModel(
            name='book_event_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event_reg_tbl')),
            ],
        ),
    ]
