# Generated by Django 4.1.6 on 2023-04-18 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_alter_booking_arrival_date_alter_booking_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_event_tbl',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_event_tbl',
            name='audient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.user_regtbl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 13, 30, 53, 246753)),
        ),
        migrations.AddField(
            model_name='book_event_tbl',
            name='status',
            field=models.CharField(default='notpaid', max_length=15),
        ),
        migrations.AddField(
            model_name='book_event_tbl',
            name='ticketno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 13, 30, 53, 240855)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 13, 30, 53, 240855)),
        ),
    ]
