# Generated by Django 4.1.6 on 2023-04-19 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_book_event_tbl_amount_book_event_tbl_audient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 12, 37, 45, 446135)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 12, 37, 45, 446135)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 12, 37, 45, 446135)),
        ),
    ]
