# Generated by Django 4.1.6 on 2023-04-21 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0004_academy_reg_tbl_dist'),
        ('User', '0027_alter_book_event_tbl_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 21, 22, 55, 524877)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 21, 22, 55, 524877)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 21, 22, 55, 524877)),
        ),
        migrations.CreateModel(
            name='Academy_admission_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('mob', models.IntegerField()),
                ('ag', models.IntegerField()),
                ('ad', models.TextField()),
                ('gn', models.CharField(max_length=10)),
                ('eml', models.EmailField(max_length=254, unique=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.academy_reg_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_regtbl')),
            ],
        ),
    ]
