# Generated by Django 4.1.6 on 2023-04-22 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_alter_book_event_tbl_bookingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy_admission_tbl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 11, 46, 12, 895619)),
        ),
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 11, 46, 12, 895619)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 29, 11, 46, 12, 895619)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 11, 46, 12, 895619)),
        ),
    ]
