# Generated by Django 4.1.6 on 2023-04-23 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_academy_admission_tbl_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_admission_tbl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 20, 41, 8, 375973)),
        ),
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 20, 41, 8, 375973)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 20, 41, 8, 375973)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 20, 41, 8, 375973)),
        ),
        migrations.CreateModel(
            name='posts_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimg', models.FileField(upload_to='pictures')),
                ('Pcaption', models.TextField(default='nocaption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_regtbl')),
            ],
        ),
    ]
