# Generated by Django 4.1.6 on 2023-04-27 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_alter_academy_admission_tbl_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf_booking_tbl',
            old_name='etime',
            new_name='entime',
        ),
        migrations.RenameField(
            model_name='turf_booking_tbl',
            old_name='stime',
            new_name='sttime',
        ),
        migrations.AlterField(
            model_name='academy_admission_tbl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 54, 47, 326700)),
        ),
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 54, 47, 326700)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 16, 54, 47, 326188)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 54, 47, 326188)),
        ),
        migrations.AlterField(
            model_name='turf_booking_tbl',
            name='tdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 54, 47, 326700)),
        ),
    ]
