# Generated by Django 4.1.6 on 2023-04-27 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0037_rename_etime_turf_booking_tbl_entime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_admission_tbl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 55, 32, 380946)),
        ),
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 55, 32, 380946)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 16, 55, 32, 380946)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 55, 32, 380946)),
        ),
        migrations.AlterField(
            model_name='turf_booking_tbl',
            name='tdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 16, 55, 32, 380946)),
        ),
    ]
