# Generated by Django 4.1.6 on 2023-04-27 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0038_alter_academy_admission_tbl_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf_booking_tbl',
            old_name='entime',
            new_name='etime',
        ),
        migrations.RenameField(
            model_name='turf_booking_tbl',
            old_name='sttime',
            new_name='stime',
        ),
        migrations.AlterField(
            model_name='academy_admission_tbl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 17, 0, 42, 852964)),
        ),
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 17, 0, 42, 852964)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 17, 0, 42, 851969)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 17, 0, 42, 851969)),
        ),
        migrations.AlterField(
            model_name='turf_booking_tbl',
            name='tdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 17, 0, 42, 853965)),
        ),
    ]
