# Generated by Django 4.1.6 on 2023-04-28 07:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0042_alter_academy_admission_tbl_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy_admission_tbl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 55, 46, 579014)),
        ),
        migrations.AlterField(
            model_name='book_event_tbl',
            name='audient',
            field=models.ForeignKey(default='this user account is deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='User.user_regtbl'),
        ),
        migrations.AlterField(
            model_name='book_event_tbl',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 55, 46, 579014)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 12, 55, 46, 579014)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 55, 46, 579014)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='this user account is deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='User.user_regtbl'),
        ),
        migrations.AlterField(
            model_name='complaint_reg_tbl',
            name='book',
            field=models.ForeignKey(default='this booking is deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='User.booking'),
        ),
        migrations.AlterField(
            model_name='turf_booking_tbl',
            name='tdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 12, 55, 46, 579014)),
        ),
        migrations.AlterField(
            model_name='turf_booking_tbl',
            name='user',
            field=models.ForeignKey(default='this user account is deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='User.user_regtbl'),
        ),
    ]
