# Generated by Django 4.1.2 on 2023-06-24 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0044_alter_academy_admission_tbl_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy_admission_tbl",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 24, 11, 12, 25, 584924)
            ),
        ),
        migrations.AlterField(
            model_name="book_event_tbl",
            name="bookingdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 24, 11, 12, 25, 584924)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="arrival_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 1, 11, 12, 25, 583920)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 24, 11, 12, 25, 583920)
            ),
        ),
        migrations.AlterField(
            model_name="turf_booking_tbl",
            name="tdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 24, 11, 12, 25, 585919)
            ),
        ),
        migrations.CreateModel(
            name="OrderTrac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Order Placed"),
                            ("SHIPPING", "Shipping"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PLACED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "orderid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.booking"
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        default="this user account is deleted",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="User.user_regtbl",
                    ),
                ),
            ],
        ),
    ]
