# Generated by Django 4.1.2 on 2023-07-19 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0054_alter_academy_admission_tbl_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="fullpayment", name="newcartid",),
        migrations.AddField(
            model_name="fullpayment",
            name="userid",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.user_regtbl",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newcartadd",
            name="status",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="academy_admission_tbl",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 19, 17, 11, 50, 261109)
            ),
        ),
        migrations.AlterField(
            model_name="book_event_tbl",
            name="bookingdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 19, 17, 11, 50, 261109)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="arrival_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 26, 17, 11, 50, 260109)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 19, 17, 11, 50, 260109)
            ),
        ),
        migrations.AlterField(
            model_name="turf_booking_tbl",
            name="tdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 19, 17, 11, 50, 262109)
            ),
        ),
    ]
