# Generated by Django 4.1.2 on 2023-08-08 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("itemseller", "0013_product_upload_tbl_catid"),
        ("User", "0062_placeoreder_sellerid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sellerid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="itemseller.itemseller_reg_tbl",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="academy_admission_tbl",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 17, 57, 136578)
            ),
        ),
        migrations.AlterField(
            model_name="book_event_tbl",
            name="bookingdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 17, 57, 135578)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="arrival_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 15, 15, 17, 57, 135578)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 17, 57, 135578)
            ),
        ),
        migrations.AlterField(
            model_name="turf_booking_tbl",
            name="tdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 17, 57, 137609)
            ),
        ),
    ]
