# Generated by Django 4.1.2 on 2023-08-08 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0063_orderitem_sellerid_alter_academy_admission_tbl_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="placeoreder", name="sellerid",),
        migrations.AlterField(
            model_name="academy_admission_tbl",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 18, 47, 912783)
            ),
        ),
        migrations.AlterField(
            model_name="book_event_tbl",
            name="bookingdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 18, 47, 911784)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="arrival_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 15, 15, 18, 47, 911784)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 18, 47, 910783)
            ),
        ),
        migrations.AlterField(
            model_name="turf_booking_tbl",
            name="tdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 8, 15, 18, 47, 913782)
            ),
        ),
    ]
