# Generated by Django 4.1.2 on 2023-08-11 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0072_comments_tbl_approve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="academy_admission_tbl",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 11, 14, 57, 17, 852706)
            ),
        ),
        migrations.AlterField(
            model_name="book_event_tbl",
            name="bookingdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 11, 14, 57, 17, 851707)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="arrival_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 18, 14, 57, 17, 851707)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 11, 14, 57, 17, 851707)
            ),
        ),
        migrations.AlterField(
            model_name="turf_booking_tbl",
            name="tdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 11, 14, 57, 17, 853739)
            ),
        ),
    ]
