# Generated by Django 4.1.2 on 2023-08-12 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0073_contact_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_event_tbl",
            name="cancel",
            field=models.CharField(default="Nill", max_length=100),
        ),
        migrations.AlterField(
            model_name="academy_admission_tbl",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 16, 25, 25, 742471)
            ),
        ),
        migrations.AlterField(
            model_name="book_event_tbl",
            name="bookingdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 16, 25, 25, 741471)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="arrival_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 19, 16, 25, 25, 741471)
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 16, 25, 25, 741471)
            ),
        ),
        migrations.AlterField(
            model_name="turf_booking_tbl",
            name="tdate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 16, 25, 25, 743471)
            ),
        ),
    ]
